<template>
  <header id="container">
    <div id="ButtonGrafic">
      <p>Daily Sales</p>
    </div>
    <div id="ButtonGrafic">
      <div>
        <p>{{ txtButtonGrafic }}</p>
      </div>
    </div>
    <div id="ButtonGrafic">
      <p>txtButtonGrafic</p>
    </div>
    <div id="ButtonGrafic">
      <p>gra</p>
    </div>
    <div id="ButtonGrafic">
      <div class="elementsInside">
        <p>gra</p>
        <p>gra</p>
        <p>gra</p>
        <p>gra</p>
      </div>
      <div id="otherLorem">
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quis dicta eaque, molestias</p>
      </div>
    </div>
    <div id="ButtonGrafic">
      <div class="boxApiItems" v-for="todo in filterCountry" :key="todo">
        <!--//* <input type="text" v-model="filter" /> -->
        <p>#stayAtHome</p>
        <p>cases</p>
        <p>
          {{ todo.cases }}
        </p>
        <img id="apiFlagImg" :src="todo.countryInfo.flag" alt="" />
      </div>
    </div>
  </header>
</template>

<script>
import axios from "axios";
export default {
  data() {
    return {
      todo: null,
      filter: "",
    };
  },
  props: {
    txtButtonGrafic: Text,
  },
  computed: {
    filterCountry() {
      if (!this.filter) return this.todo;
      return this.todo.filter((todo) =>
        todo.country.toLowerCase().includes(this.filter.toLowerCase())
      );
    },
  },
  mounted() {
    this.getApiWorld();
  },
  async mounted() {
    try {
      const results = await axios.get(`https://corona.lmao.ninja/v2/countries`);
      this.todo = results.data.filter((dataSearchBrazil) => {
        return dataSearchBrazil.country === "Brazil";
      });
      console.log(data);
    } catch (error) {
      console.log(error);
    }
  },
};
</script>

<style scoped>
/* ----------------------------------------------
 * Generated by Animista on 2021-9-21 9:56:41
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
.boxApiItems {
  display: flex;
  width: auto;
  height: auto;
}
#apiFlagImg {
  border-radius: 5px;
  width: 100px;
  height: 70px;
}
#apiFlagImg {
  -webkit-animation: apiFlagImg 0.4s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  animation: apiFlagImg 0.4s cubic-bezier(0.39, 0.575, 0.565, 1) both;
}
@-webkit-keyframes apiFlagImg {
  0% {
    -webkit-transform: scale(0.5);
    transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}
@keyframes apiFlagImg {
  0% {
    -webkit-transform: scale(0.5);
    transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}

#container {
  padding: 5px;
  height: 1fr;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-wrap: wrap;
}
#ButtonGrafic {
  display: flex;
  background: #d4cdcd;
  align-items: center;
  flex-direction: column;
  justify-content:space-evenly;
  width: 350px;
  height: 230px;
  margin: 10px;
  border-radius: 0.2rem;
}
#ButtonGrafic:nth-child(1) {
  background: rgb(250, 250, 250);
}
#ButtonGrafic:nth-child(2) {
  background: rgb(162, 0, 255);
}
#ButtonGrafic:nth-child(3) {
  background: rgb(179, 255, 0);
}

#ButtonGrafic:nth-child(4) {
  background: red;
  height: 190px;
}

#ButtonGrafic:nth-child(5) {
  background: rgb(0, 255, 106);
  height: 190px;
}
#ButtonGrafic:nth-child(6) {
  background: rgb(0, 102, 255);
  height: 190px;
  display: flex;
  justify-content: center;
}
#ButtonGrafic {
  -webkit-animation: ButtonGrafic 0.5s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  animation: ButtonGrafic 0.5s cubic-bezier(0.39, 0.575, 0.565, 1) both;
}
@-webkit-keyframes ButtonGrafic {
  0% {
    -webkit-transform: scale(0.5);
    transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}
@keyframes ButtonGrafic {
  0% {
    -webkit-transform: scale(0.5);
    transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}
.elementsInside{
  display:flex;
  width: 100%;
  height: 50%;
  flex-direction:column;
  align-items: center;
  justify-content: space-evenly;
  background: whitesmoke;
}
#otherLorem{
  width:auto;
  height: auto;
}
</style>
